### ISSUE TITLE
Better Usage Instructions

### ISSUE THREAD

**Issue by Lorenzo45** [AuliaYF/easyraikit-python#1]
I'm new to Nano development and am trying to make a server that is capable of sending Nano. This library looked helpful in getting me set up quickly, however I have no idea how to use it. Does it require having a Nano node? Where is this code supposed to run? What exactly are the fields in the config? I can't even get test.py to run properly and I've tried creating a node, entering the server address, and entering my wallet ID and private key in the config.

Any help would be greatly appreciated! Thanks!

**Comment by AuliaYF** [comment]
Hi, sorry for the delay, I created this library for Raiblocks, I don't know for sure if this will work with Nano. I no longer maintain this library as I left Raiblock since last year.
